version: '3'
services:
  nginx:
   container_name: nginx-reverse-proxy
   image: nginx:latest
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - expensetrackerbackend
   - expensetrackerfrontend

  expensetrackerbackend:
    container_name: backend
    image: docker.pkg.github.com/muellernicolas/expense-tracker-backend/expensetrackerbackend:latest
    ports:
    - 8080:8080
    
   
  expensetrackerfrontend:
    container_name: frontend
    image: docker.pkg.github.com/muellernicolas/expense-tracker-frontend/expense-tracker-frontend:latest
    ports:
    - 8081:80
    
    




