version: '3'
services:
  nginx:
   container_name: nginx-reverse-proxy
   image: nginx:latest
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - expensetrackerbackend
   - expensetrackerfrontend

  expensetrackerbackend:
    container_name: backend
    image: muellernicolas/expense-tracker-backend:latest
    ports:
    - 8080:8080
    depends_on:
    - mongodatabase
    
   
  expensetrackerfrontend:
    container_name: frontend
    image: muellernicolas/expense-tracker-frontend:latest
    ports:
    - 8081:80
  
  mongodatabase:
    image : mongo
    container_name: mongodb
    volumes:
    - 'mongodata:/data/db'
    ports:
    - 27017:27017
    restart: unless-stopped


volumes:
  mongodata:
    
    




